### PR TITLE
Couchbase templates for OpenShift - default to RHCC for images

### PR DESCRIPTION
**Pull request by jsm84**
New functionality to accompany the upcoming Technical Implementation Guide for Couchbase Server on OpenShift.

### CODE REVIEW

**Comment by tleyden** [comment]
@jsm84 merging this, but this repo is deprecated in favor of the Couchbase Operator.  (It looks like these kubernetes files depend on having that running?)

**Comment by tleyden** [comment]
> (It looks like these kubernetes files depend on having that running?)

Actually I take it back, I don't see the [expected params](https://blog.couchbase.com/introducing-couchbase-operator/)

**Comment by jsm84** [comment]
I apologize for not responding sooner, as I was out at Summit all last week. These files are totally separate from the k8s operators. These are templates which would deploy (sans operator) into OpenShift by using `oc create -f couchbase-server-ephemeral` and then running `oc new-app couchbase-server-ephemeral`. The parameters used here won't match what is necessary to deploy the operator. These templates are necessary for the Technical Implementation Guide, which is co-authored by Couchbase and Red Hat (slated for publishing today). We will be doing another version of the guide over the summer, which will cover the operator method.

**Comment by tleyden** [comment]
> These are templates which would deploy (sans operator) into OpenShift ..

Ok thanks, but why would anyone deploy Couchbase sans operator at this point?   Or are you saying this is just an interim solution until the second guide due out this summer that covers the operator method?

**Comment by jsm84** [comment]
Correct. This is essentially a hold over until the operator comes out of beta and a corresponding image is published in the Red Hat Container Catalog. You can leave this closed, as I've forked the repo and am hosting the necessary content for the recently published guide.On May 17, 2018 14:26, Traun Leyden <notifications@github.com> wrote:
These are templates which would deploy (sans operator) into OpenShift ..

Ok thanks, but why would anyone deploy Couchbase sans operator at this point?   Or are you saying this is just an interim solution until the second guide due out this summer that covers the operator method?

**Pull request closed without merging**
